# This is a basic workflow to help you get started with Actions
name: Convert Jupyter Notebook and deploy to GitHub Pages

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Convert-Deploy"
  Convert-Deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out the repository
        uses: actions/checkout@v3
      
      # Updates Node.js version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      # List all files in repo
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Try to implement Docker caching
      - name: Configure Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ifsc:latest
      
      - name: Try to display things
      #   run: echo "${PWD}" #/home/runner/work/scraping-IFSC-website-via-selenium/scraping-IFSC-website-via-selenium
        run: docker ps
        # run: docker exec ifsc pwd

      # - name: Try to create subdir and convert
      #   run: |
      #     docker run -v ${PWD}/docs:/app/docs ifsc make convert

      # Converts
      # - name: Convert Notebook to HTML
        # run: docker run -v $PWD/docs:/app/docs mycontainer make convert
        # run: docker run -v $PWD:/app/docs ifsc make convert
        # run: docker run -v ${{ secrets.DOCKERHUB_USERNAME }}/ifsc/app/docs ifsc make convert

      # - name: List files in the docs folder
      #   run: |
      #     ls docs
      # - name: Build Docker image
      #   run: docker build -t mycontainer . -f Dockerfile